spring:
  profiles:
    active:
      #- local
      - p6spy
    include:
      - test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        #dialect: org.hibernate.dialect.oracle10gDialect
        use_sql_comments: false # JPQL???????

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        #one-indexed-parameters: true # paging 1

logging:
  level:
    p6spy: info
    org.hibernate.SQL: debug
    #org.hibernate.type: trace